server:
    port: 3333
    context-path: #/liuzh/

logging:
    level:
        tk.mybatis: DEBUG

spring:
    datasource:
#        url: jdbc:sqlserver://192.168.16.200:1433;DatabaseName=test
#        username: sa
#        password: 123456
#        # 使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        name: test
        url: jdbc:mysql://127.0.0.1:3306/test
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver    

    http:
        encoding:
            charset: utf8
            force: true
            enabled: true
    mvc:
        view:
            prefix: /templates/
            suffix: .html
            
    freemarker:
        cache: false
        request-context-attribute: request





#以下属性不可用
#mybatis:
#    pagehelper:
#        dialect: mysql
#        reasonable: true
#        supportMethodsArguments: true
#        returnPageInfo: check
#        params: count=countSql
#    mapper:
#        mappers: tk.mybatis.springboot.util.MyMapper
#        notEmpty: true
#        style: camelhump
#    sqlSessionFactoryBean:
#        mapperLocations:
#            - classpath:mapper/*.xml
#            - classpath:mapper2/*.xml
#        typeAliasesPackage: tk.mybatis.springboot.model
#    mapperScanner:
#        basePackage: tk.mybatis.springboot.mapper
